{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set name = data.get('name')|replace("tethysapp-", "")|lower %}

package:
  name: {{ name }}
  version: {{ data.get('version') }}

about:
  author: {{ data.get('author')}}
  description: {{ data.get('description')}}
  license: "{'name': 'release_package', 'version': '0.1.10', 'description': 'An app for visualizing and consuming grided data hosted on a THREDDS Data Server', 'long_description': '', 'author': 'Enoch Jones', 'author_email': 'jon.enoch.jones@gmail.com', 'url': 'https://github.com/BYU-Hydroinformatics/tethysapp-metdataexplorer', 'license': ''}"
  dev_url: {{ data.get('url') }}

outputs:
  - name: {{ name }}
extra:
  author_email: jon.enoch.jones@gmail.com
  keywords:
  - n
  - e
  - t
  - C
  - D
  - F
  recipe-maintainers:
  - TethysAppWarehouse

build:
  noarch: python
  preserve_egg_dir: true
  script: python setup.py install --record=record.txt
requirements:
  build:
  - python
  run:
  - requests
  - siphon
  - netCDF4
  - numpy
  - geopandas
  - pandas
  - geojson
  - xarray
  - pygrib
  - cfgrib
source:
  path: ..
